class Jems:
  def __init__(self):
    self.jems = [
        "agate",
        "azurite",
        "quartz",
        "hematite",
        "lapis lazuli",
        "malachite",
        "obsidian",
        "rhodochrosite",
        "tiger eye",
        "turquoise",
        "pearl ",
        "bloodstone",
        "carnelian",
        "chalcedony",
        "chrysoprase",
        "citrine",
        "iolite",
        "jasper",
        "moonstone",
        "onyx",
        "peridot",
        "rock crystal",
        "sard",
        "sardonyx",
        "zircon",
        "amber",
        "amethys",
        "chrysoberyl",
        "coral",
        "garnet ",
        "jade",
        "spinel ",
        "tourmaline",
        "alexandrite",
        "aquamarine",
        "garnet ",
        "topaz",
        "emerald",
        "opal",
        "sapphire ",
        "corundum",
        "sapphire",
        "ruby",
        "diamond",
        "jacinth"
    ]
