name: deploy keggy
on:
  push:
    branches: [ main, keggy-workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update and restart Keggy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          if ps ax | grep -v grep | grep keggy.py; then
            pkill -f keggy.py > /dev/null
          fi
          sleep 3
          cd keggy
          sleep 3
          git pull
          sleep 3
          nohup python3 keggy.py &
          exit
          