name: deploy keggy
on:
  push:
    branches: [ main, keggy-workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update and restart Keggy
      run: |
        echo "${{secrets.KEGGY_PEM}}" > keggy_vm_key.pem
        mv keggy_vm_key.pem ~/.ssh/
        ssh -i ~/.ssh/keggy_vm_key.pem keggy_vm@{{secrets.KEGGY_IP}}
        ${{secrets.PASSPHRASE}}
        # cd keggy
        # pkill -9 -f keggy.py
        # git pull
        # nohup python3 keggy.py &