name: deploy keggy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update and Restart Keggy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          for pid in $(ps -ef |
            awk -v first="$1" -v second="$2" -v app="keggy.py" '
              $0 ~ first && $0 ~ second && $0 ~ app && !/awk/ {print $2}')
          do
            kill "$pid"
          done
          sleep 3
          cd keggy
          git pull -q 2>&1 | cat
          sleep 3
          nohup python3 keggy.py >/dev/null 2>&1 &
          exit

  publish_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Versioning Data
      id: versioning
      uses: Soumeh/Auto-Versioning@main
      
    - name: Create Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.event.head_commit.message }}
        tag: ${{ steps.versioning.outputs.tag }}
        body: "${{ steps.versioning.outputs.changelog }}"
        gzip: false
